using System;
using System.Collections.Generic;

namespace CAMSGHB.CAMS.API.Models
{
    public partial class Appraisalnfo
    {
        public Appraisalnfo()
        {
            AppraisalInfoDetail = new HashSet<AppraisalInfoDetail>();
            CondAssetOutdoor = new HashSet<CondAssetOutdoor>();
        }

        public long AppraisalInfoId { get; set; }
        public long? AppraisalId { get; set; }
        public long? DetCollatId { get; set; }
        public long? HostCollatId { get; set; }
        public string CheckDocument { get; set; }
        public string OtherDetail1 { get; set; }
        public string LandPosition { get; set; }
        public string CheckBy { get; set; }
        public string CheckByOther { get; set; }
        public string Street { get; set; }
        public string SplitEntry { get; set; }
        public double? Distance { get; set; }
        public string LandCondition { get; set; }
        public double? AvgLandReclamation { get; set; }
        public double? LandLevel { get; set; }
        public string WithBuilding { get; set; }
        public int? WithBuildingQty { get; set; }
        public string WithBuildingNumber { get; set; }
        public double? WithBuildingResult { get; set; }
        public string ConstProgExpand { get; set; }
        public double? ConstProgExpandPct { get; set; }
        public int? OtherBuildings { get; set; }
        public string Number2 { get; set; }
        public double? ConstructionResult1 { get; set; }
        public string WithBuildingAsesNumber { get; set; }
        public double? RoadSurfaceWidth { get; set; }
        public double? PedestrianWay { get; set; }
        public string RoadToLand { get; set; }
        public string CarAccess { get; set; }
        public string RoadSurface { get; set; }
        public string RoadSurfaceOther { get; set; }
        public string Electric { get; set; }
        public string WaterGroundwater { get; set; }
        public string Drain { get; set; }
        public string ElectricRoad { get; set; }
        public string OtherUtility { get; set; }
        public string Otherutilitydetail { get; set; }
        public string EntranceExit { get; set; }
        public string EntranceExitOther { get; set; }
        public string IsExpropriation { get; set; }
        public string Expropriation { get; set; }
        public string InLineExpropriated { get; set; }
        public string SectionScaleEncr { get; set; }
        public double? SpaceEncroached { get; set; }
        public string ElectricityOver100M { get; set; }
        public double? ElectricityOver100Mnote { get; set; }
        public string CarNoAccess { get; set; }
        public string LocatedForestAgriPark { get; set; }
        public string HighVoltageLine { get; set; }
        public string InfringementOther { get; set; }
        public string FeatureLand { get; set; }
        public string RemarkLand { get; set; }
        public string TypeOfCollateral { get; set; }
        public string OtherInfringement { get; set; }
        public double? LandAssessment { get; set; }
        public double? AppraisedPrice { get; set; }
        public double? LandPrice { get; set; }
        public double? BuildingPrice { get; set; }
        public double? PriceIncluding { get; set; }
        public double? NumberOfFloors { get; set; }
        public string AppripriceType { get; set; }
        public double? Guarantee2 { get; set; }
        public double? Guarantee { get; set; }
        public string OtherDetail2 { get; set; }
        public string BuildingNum { get; set; }
        public string HouseNo { get; set; }
        public string ConstDeedNo { get; set; }
        public string ConstSite { get; set; }
        public string ConstSiteSize { get; set; }
        public string Construction { get; set; }
        public double? ConstructionPct { get; set; }
        public int? BuildingYr { get; set; }
        public string DefectiveWork { get; set; }
        public string IsResidential { get; set; }
        public string IsResidentialOther { get; set; }
        public bool AlreadyBuiltChk { get; set; }
        public string AlreadyBuiltY { get; set; }
        public string AlreadyBuiltM { get; set; }
        public string BuildingType { get; set; }
        public string BuildingTypeOther { get; set; }
        public string BuildingModel { get; set; }
        public double? NoOfFloor { get; set; }
        public double? ResidentialArea { get; set; }
        public bool InTheMunicipality { get; set; }
        public string OtherMunicipality { get; set; }
        public string RoofFrame { get; set; }
        public string RoofFrameOther { get; set; }
        public string Roof { get; set; }
        public string RoofOther { get; set; }
        public string Ceiling { get; set; }
        public string CeilingOther { get; set; }
        public string Painting { get; set; }
        public string PaintingOther { get; set; }
        public string Floor1 { get; set; }
        public string Floor1Surface { get; set; }
        public string OthFloor1Surface { get; set; }
        public string Floor1Material { get; set; }
        public string OthFloor1MaterialOther { get; set; }
        public string Floor2 { get; set; }
        public string Floor2Surface { get; set; }
        public string OthFloor2Surface { get; set; }
        public string Floor2Material { get; set; }
        public string OthFloor2MaterialOther { get; set; }
        public string Floor3 { get; set; }
        public string Floor3Surface { get; set; }
        public string OthFloor3Surface { get; set; }
        public string Floor3Material { get; set; }
        public string OthFloor3MaterialOther { get; set; }
        public string Floor4 { get; set; }
        public string Floor4Surface { get; set; }
        public string OthFloor4Surface { get; set; }
        public string Floor4Material { get; set; }
        public string OthFloor4MaterialOther { get; set; }
        public string Fence { get; set; }
        public string FenceOther { get; set; }
        public string ConstType { get; set; }
        public string Village { get; set; }
        public string UtilOfBuilding { get; set; }
        public string UtilOfBuildingOther { get; set; }
        public string ResidentialAreaCommercialBuilding { get; set; }
        public string RemarkBuilding { get; set; }
        public double? BuildingPriceBefore { get; set; }
        public double? DegenerativeCondition { get; set; }
        public double? DepreciationPerYear { get; set; }
        public double? Notpainted { get; set; }
        public double? Total { get; set; }
        public double? Amount2 { get; set; }
        public double? BuildingpriceAfterDepreciation { get; set; }
        public string Coordinatesfrom { get; set; }
        public string PositionLatitude { get; set; }
        public string PositionLongtitude { get; set; }
        public string ChkInfoCollMarket { get; set; }
        public string AnalyCompareMarket { get; set; }
        public string RoomNo { get; set; }
        public string FloorNoCondo { get; set; }
        public string FloorNoActual { get; set; }
        public double? TotLivSpace { get; set; }
        public string Decoration { get; set; }
        public string FloorMaterial { get; set; }
        public string FloorMaterialOther { get; set; }
        public string BathroomFlrMaterial { get; set; }
        public string BathroomFlrMaterialOther { get; set; }
        public double? NoOfSection { get; set; }
        public double? NoOfPart { get; set; }
        public string CondoName { get; set; }
        public string BuildingNo { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public int? AreaNgan { get; set; }
        public int? AreaRai { get; set; }
        public double? AreaWa { get; set; }
        public string RegisterNumber { get; set; }
        public bool ChkDeedCompare { get; set; }
        public string ChkDeedDetail { get; set; }
        public string Building { get; set; }
        public int? TotalNoFloor { get; set; }
        public string BuildingStyle { get; set; }
        public string ConstructionMaterials { get; set; }
        public string CondoRoof { get; set; }
        public string CondoRoofOth { get; set; }
        public string Lift { get; set; }
        public string Hallway { get; set; }
        public string Parking { get; set; }
        public string FireEscape { get; set; }
        public string FireHydrant { get; set; }
        public string Pool { get; set; }
        public string GymRoom { get; set; }
        public string Park { get; set; }
        public string Stadium { get; set; }
        public string Club { get; set; }
        public string SaunaRoom { get; set; }
        public string SecuritySystem { get; set; }
        public string KeyCardSystem { get; set; }
        public string LegalEntity { get; set; }
        public string WasteDisposalSystem { get; set; }
        public string UtilityOther { get; set; }
        public string UtilityOtherDetail { get; set; }
        public string Remark { get; set; }
        public double? SumAssetOutdoorSpace { get; set; }
        public double? UnitPrice { get; set; }
        public double? AcceptPrice { get; set; }
        public double? SumAcceptPrice { get; set; }
        public string DiffGradeEffectPric { get; set; }
        public bool NumberBuildChk { get; set; }
        public int? TotalNumBuilding { get; set; }
        public DateTime? DateLastReport { get; set; }
        public bool ReportChk { get; set; }
        public string BankAnaly { get; set; }
        public string Wall { get; set; }
        public string WallOther { get; set; }
        public double? FireInsuranceAreaPerSqM { get; set; }
        public string ListCheckBuilding { get; set; }
        public long CollateralListId { get; set; }

        public CollateralList CollateralList { get; set; }
        public ICollection<AppraisalInfoDetail> AppraisalInfoDetail { get; set; }
        public ICollection<CondAssetOutdoor> CondAssetOutdoor { get; set; }
    }
}
